Cleanup scripts (in particular dev-env & MongoDB) Mongo now runs attached for development with `just start-deps`

diff --git a/scripts/setup-mongodb b/scripts/setup-mongodb
--- a/scripts/setup-mongodb
+++ b/scripts/setup-mongodb
@@ -1,29 +1,19 @@
 #!/bin/bash
+set -e
 
-# Sets up MongoDB (engine and data) for server app(s).
-# Meant to be run from dev env setup scripts.
+# Sets up MongoDB (engine and data) for server app(s)
+# Meant to be run from dev env setup scripts
+
+# Check OS and prepare download URL
 # https://www.mongodb.com/try/download/community
 if [ `uname` = "Linux" ]; then
-  export MONGO_NAME=mongodb-linux-x86_64-ubuntu1804-v4.2-latest
-  export MONGO_DL_BASE_URL=https://fastdl.mongodb.org/linux
-elif [ `uname` = "Darwin" ]; then # OSX
-  export MONGO_NAME=mongodb-macos-x86_64-4.2.8
-  export MONGO_DL_BASE_URL=https://fastdl.mongodb.org/osx
+  MONGO_NAME=mongodb-linux-x86_64-ubuntu1804-v4.2-latest
+  MONGO_DL_BASE_URL=https://fastdl.mongodb.org/linux
+elif [ `uname` = "Darwin" ]; then # MacOS
+  MONGO_NAME=mongodb-macos-x86_64-4.2.8
+  MONGO_DL_BASE_URL=https://fastdl.mongodb.org/osx
 else
-  echo "Installation is meant to be on Linux or OSX"
-  exit 1
-fi
-
-export MONGO_DATA_FOLDER=$DATA_FOLDER/mongodb-data
-export MONGO_LOGS_FOLDER=$DATA_FOLDER/mongodb-logs
-
-if [[ -z "$MONGO_BASE_FOLDER" ]]; then
-  echo ""
-  echo "Expected environment variables:"
-  echo "    MONGO_BASE_FOLDER Root installation folder; created if missing"
-  echo ""
-  echo "MongoDB will be installed (if needed) in \"MONGO_BASE_FOLDER/MONGO_NAME\""
-  echo ""
+  echo "Installation is meant to be on Linux or MacOS"
   exit 1
 fi
 
@@ -31,52 +21,46 @@ fi
 SCRIPT_FOLDER=$(cd $(dirname "$0"); pwd)
 cd $SCRIPT_FOLDER/
 
-mkdir -p $MONGO_BASE_FOLDER
+# Check & create file structure
+
+MONGO_FOLDER_NAME=mongodb-bin
+
+if [[ -z "$VAR_PRYV_FOLDER" ]]; then
+  echo ""
+  echo "Error: Missing environment variable VAR_PRYV_FOLDER (root installation folder)"
+  echo "(MongoDB will be installed (if needed) in 'VAR_PRYV_FOLDER/$MONGO_FOLDER_NAME')"
+  echo ""
+  exit 1
+fi
+
+mkdir -p $VAR_PRYV_FOLDER
+
+MONGO_DATA_FOLDER=$VAR_PRYV_FOLDER/mongodb-data
 mkdir -p $MONGO_DATA_FOLDER
+
+MONGO_LOGS_FOLDER=$VAR_PRYV_FOLDER/mongodb-logs
 mkdir -p $MONGO_LOGS_FOLDER
 
-if [[ ! -d $MONGO_BASE_FOLDER ]]; then
-  echo ""
-  echo "Invalid base folder path: '$MONGO_BASE_FOLDER' does not exist"
-  echo ""
-  exit 1
-fi
-
-if [[ ! -d $MONGO_DATA_FOLDER ]]; then
-  echo ""
-  echo "Invalid data folder path: '$MONGO_DATA_FOLDER' does not exist"
-  echo ""
-  exit 1
-fi
-
 echo ""
-MONGO_FOLDER_NAME=mongodb-bin
-echo "Checking for MongoDB ($MONGO_BASE_FOLDER/$MONGO_FOLDER_NAME)..."
-if [[ ! -d $MONGO_BASE_FOLDER/$MONGO_FOLDER_NAME ]]; then
+echo "Checking for MongoDB ($VAR_PRYV_FOLDER/$MONGO_FOLDER_NAME)..."
+if [[ ! -d $VAR_PRYV_FOLDER/$MONGO_FOLDER_NAME ]]; then
   echo "...installing $MONGO_NAME"
   echo ""
-  EXIT_CODE=0
-  curl -C - -o "$MONGO_BASE_FOLDER/$MONGO_NAME.tgz" $MONGO_DL_BASE_URL/$MONGO_NAME.tgz
-  EXIT_CODE=`expr ${EXIT_CODE} + $?`
-  cd $MONGO_BASE_FOLDER
-  mkdir $MONGO_FOLDER_NAME
-  tar -xzf $MONGO_NAME.tgz -C $MONGO_FOLDER_NAME --strip-components 1  # extract into standardized mongo folder name to be os-independant
-  EXIT_CODE=`expr ${EXIT_CODE} + $?`
-  rm $MONGO_NAME.tgz
-  if [[ ${EXIT_CODE} -ne 0 ]]; then
-    echo ""
-    echo "Failed installing MongoDB. Setup aborted."
-    echo ""
-    exit $((${EXIT_CODE}))
-  fi
-else
-  echo "...skipped: $MONGO_FOLDER_NAME already installed"
-fi
 
+  curl -C - -o "$VAR_PRYV_FOLDER/$MONGO_NAME.tgz" $MONGO_DL_BASE_URL/$MONGO_NAME.tgz
+
+  cd $VAR_PRYV_FOLDER
+  # extract into standardized mongo folder name to be OS-independant
+  mkdir $MONGO_FOLDER_NAME
+  tar -xzf $MONGO_NAME.tgz -C $MONGO_FOLDER_NAME --strip-components 1
+  rm $MONGO_NAME.tgz
+else
+  echo "...already installed"
+fi
 
 echo ""
 echo "Database setup complete."
 echo ""
-echo "To run MongoDB (--dbpath defaults to /data/db if not specified):"
-echo "    $MONGO_BASE_FOLDER/$MONGO_NAME/bin/mongod --dbpath $MONGO_DATA_FOLDER [<other arguments>]"
+echo "To run MongoDB:"
+echo "    ./scripts/start-mongo"
 echo ""
